### ISSUE TITLE
Unable to install the Ribbon interface

### ISSUE THREAD

**Issue by raindropsfromsky** [geolta/FreeCAD-Ribbon#1]
I followed the installation process, and restarted FreeCAD, but the new ribbon interface does not appear.

I have FreeCAD 20.2 on Windows 11.
The default FreeCAD works very well.

I downloaded the zip as shows below.
![image](https://github.com/geolta/FreeCAD-Ribbon/assets/9047168/605b04a2-a2e1-4277-8c3c-5dbd7b0efdac)

Then I unzipped it and moved the folder to C:\Program Files\Util\FreeCAD 0.20\Mod
(All my apps are placed in a subfolder called "Util")

Then I restarted FreeCAD. But the new ribbon interface has not come up.

Please let me know if I have followed the procedure correctly.

BTW your installation instructions state that more information is provided [here](https://wiki.freecad.org/Installing_more_workbenches). But that page is about installing workbenches, and not about ribbon UI.
(The difference is that the Ribbon UI option is not supposed to appear in the workbench drop-down list.)
So, to that extent, this instruction is confusing. Was that a mistake?

**Comment by geolta** [comment]
Yes, you have to install pyqtribbon in the first place (can be done with `pip install pyqtribbon`) then it shall work.

> BTW your installation instructions state that more information is provided [here](https://wiki.freecad.org/Installing_more_workbenches). But that page is about installing workbenches, and not about ribbon UI. (The difference is that the Ribbon UI option is not supposed to appear in the workbench drop-down list.) So, to that extent, this instruction is confusing. Was that a mistake?

Yeah, that's right, technically it isn't a workbench, I linked this wiki page to give state somewhere where the unzipped folder has to be extracted.

**Comment by geolta** [comment]
I updated the installation instructions in the README.

**Comment by luzpaz** [comment]
Is this still relevant ?

**Comment by geolta** [comment]
No, this shoudn't be relevant anymore, thank you for the hint :)
