### ISSUE TITLE
It's not working on freecad 0.21.2 despite dependencies installed

### ISSUE THREAD

**Issue by fannkadhedia027** [geolta/FreeCAD-Ribbon#10]
I have a problem with this addon. I know it's a test but i'm testing in 0.21.2 until i have to reinstall them all the time again and agin just to recieve the same error and the ribbon not working.  Any idea?

**Comment by geolta** [comment]
This should be fixed now, please download the latest version and test again :)

**Comment by fannkadhedia027** [comment]
it runs good, i tried them on 0.22, it runs good
