### ISSUE TITLE
"No module named 'qtpy' error when launching FreeCAD

### ISSUE THREAD

**Issue by mich-j** [geolta/FreeCAD-Ribbon#8]
Hello!

I wanted to try out the Ribbon add-on, I put the FreeCAD-Ribbon folder into the `Mod` directory, but I get an error when launching FreeCAD:

```
During initialization the error "No module named 'qtpy'" occurred in /home/<username>/.var/app/org.freecadweb.FreeCAD/data/FreeCAD/Mod/FreeCAD-Ribbon/InitGui.py
```

Since I'm on Ubuntu, I cannot install system-wide packages via `pip`. I have installed the following packages via `apt`:
 
```
sudo apt install python3-qtpy
sudo apt install python3-pyside2*
```

Unfortunately, this error still persists.

My setup details:

```
Ubuntu 23.10 x86_64 
OS: KDE Flatpak runtime (ubuntu:GNOME/ubuntu-wayland)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.4
  * FreeCAD-Ribbon
  * boltsfc 2022.11.5
  * 3D_Printing_Tools
```

**Comment by samuk** [comment]
I also have this error on Debian Bookworm

Although in my case sudo apt install python3-qtpy did fix it

**Comment by geolta** [comment]
This should be fixed now, please download the latest version :)
